#PM_diagnostic:
#  description: >
#    Use the tools that you have to understand and decompose the process. The order of the tools you should use is: choosing_approach_tool, abstraction_tool and then process_analysis_tool.  For the choosing_approach, if the output is not close to "DFG" or "Temporal Profile" or "Variants" then run it again. For the abstraction tool, the first input is {filename} and the second is what the choosing_approach had as output.
#  expected_output: >
#    A detailed description (with examples) of the most important areas in the event log. They can be bottlenecks or really crucial/large events in the event log.
#  agent: PM_agent

DK_company_search:
  description: >
    Conduct a thorough research about {company} using the background memory of {process} if you have it. Use the tavily_search_company tool and make sure that the research has many references.
  expected_output: >
    A thorough research with many references, expecting at least 20 full references.
  agent: DK_company_agent

DK_process_search:
  description: >
    Conduct a thorough research about the {process} process using the background memory of {company} if you have it. Use the tavily_search_process tool and make sure that the research has many references.
  expected_output: >
    A thorough research with many references, expecting at least 20 full references.
  agent: DK_process_agent

writing_task:
  description: >
    Review the contents from both researches and the PM diagnostic task and weave them together into a coherent report of at least 1500 words which combines the {process} with the {company} with the steps from the result of the PM_agent analysis / PM_diagnostic task. 
    You may leave out information that seems irrelevant. Provide links for references if possible.     Use at least 20 relevant references in the paper (if possible) and at most 40 references.

  expected_output: >
    Formatted as markdown without '```', at least a 1500 word essay. 
    You can combine the knowledge and weave them into a well-analysed report 
    and it is extremely important that every paragraph links to a process from 
    the outputs: {skip_analysis} and {skip_flow}, and reference to the particular step that you are talking about 
    using the format 'Send Purchase Order -> Receive Goods'. It is important that 
    in every paragraph you fully reference to at least one source link from the research agents AND to a relevant step from the results of the PM_agent / the PM diagnostic task.
    Add an overview of all the used references at the bottom of the report in this format:
    ## References

    - [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8437773/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8437773/)
    - [https://www.capgemini.com/wp-content/uploads/2017/07/streamlining-the-order-to-cash-process.pdf](https://www.capgemini.com/wp-content/uploads/2017/07/streamlining-the-order-to-cash-process.pdf)
    - [https://www.mckinsey.com/capabilities/operations/our-insights/a-practical-approach-to-supply-chain-risk-management](https://www.mckinsey.com/capabilities/operations/our-insights/a-practical-approach-to-supply-chain-risk-management)
    - [https://www.mckinsey.com/industries/consumer-packaged-goods/our-insights/cpg-operations-how-to-win-in-a-rapidly-changing-environment](https://www.mckinsey.com/industries/consumer-packaged-goods/our-insights/cpg-operations-how-to-win-in-a-rapidly-changing-environment)

  agent: writing_agent
